package co.com.datatools.c2.ws.comparendo.solicitudocn.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.13 Tue Apr 05 09:42:11 COT 2016 Generated source version: 2.7.13
 */

@XmlRootElement(
        name = "solicitarNumeroComparendo",
        namespace = "http://solicitudocn.comparendo.ws.c2.datatools.com.co/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "solicitarNumeroComparendo", namespace = "http://solicitudocn.comparendo.ws.c2.datatools.com.co/")
public class SolicitarNumeroComparendo {

    @XmlElement(name = "solicitudNumeroComparendo")
    private co.com.datatools.c2.dto.ws.SolicitudNumeroComparendoWSDTO solicitudNumeroComparendo;

    public co.com.datatools.c2.dto.ws.SolicitudNumeroComparendoWSDTO getSolicitudNumeroComparendo() {
        return this.solicitudNumeroComparendo;
    }

    public void setSolicitudNumeroComparendo(
            co.com.datatools.c2.dto.ws.SolicitudNumeroComparendoWSDTO newSolicitudNumeroComparendo) {
        this.solicitudNumeroComparendo = newSolicitudNumeroComparendo;
    }

}
