package co.com.datatools.c2.enumeraciones;

public enum EnumCampoArchivoSimit {

    CONSECUTIVO(5), //
    NUMERO_COMPARENDO(20), //
    FECHA_IMPOSICION_COMPARENDO(10), //
    HORA_IMPOSICION_COMPARENDO(4), //
    DIRECCION_LUGAR_INFRACCION(80), //
    MUNICIPIO(8), //
    LOCALIDAD(30), //
    PLACA_VEHICULO(6), //
    MATRICULADO_EN(8), //
    TIPO_VEHICULO(2), //
    CLASE_SERVICIO(1), //
    RADIO_ACCION(1), //
    MODALIDAD_TRANSPORTE(1), //
    TRANSPORTE_PASAJEROS(1), //
    NUMERO_DOCUMENTO_INFRACTOR(15), //
    TIPO_DOCUMENTO_INFRACTOR(1), //
    NOMBRES_INFRACTOR(18), //
    APELLIDOS_INFRACTOR(20), //
    EDAD_INFRACTOR(2), //
    DIRECCION_INFRACTOR(40), //
    CORREO_ELECTRONICO_INFRACTOR(40), //
    TELEFONO_INFRACTOR(15), //
    CIUDAD_RESIDENCIA_INFRACTOR(8), //
    NUMERO_LICENCIA_CONDUCCION(14), //
    CATEGORIA_LICENCIA_CONDUCCION(2), //
    ORGANISMO_EXPIDE_LICENCIA(8), //
    FECHA_VENCIMIENTO_LICENCIA_CONDUCCION_INFRACTOR(10), //
    TIPO_INFRACTOR(1), //
    NUMERO_LICENCIA_TRANSITO(16), //
    ORGANISMOLICENCIA_TRANSITO(8), //
    NUMERO_DOCUMENTO_PROPIETARIO(8), //
    TIPO_DOCUMENTO_PROPIETARIO(1), //
    NOMBRES_APELLIDOS_PROPIETARIO(50), //
    RAZON_SOCIAL(30), //
    NUMERO_DOCUMENTO_EMPRESA(15), //
    NUMERO_TARJETA_OPERACION(10), //
    PLACA_AGENTE_TRANSITO(10), //
    OBSERVACIONES_AGENTE(50), //
    EXISTE_FUGA_INFRACTOR(1), //
    REPORTA_ACCIDENTE(1), //
    REPORTA_INMOVILIZACION(1), //
    NOMBRE_PATIO(30), //
    DIRECCION_PATIO_INMOVILIZACION(30), //
    NUMERO_GRUA(10), //
    PLACA_GRUA(6), //
    CONSECUTIVO_INMOVILIZACION(15), //
    NUMERO_DOCUMENTO_TESTIGO(15), //
    NOMBRES_APELLIDOS_TESTIGO(50), //
    DIRECCION_TESTIGO(40), //
    NUMERO_CELULAR_TESTIGO(15), //
    VALOR_COMPARENDO(8), //
    VALORES_ADICIONALES(8), //
    ORGANISMO_REPORTA(8), //
    ESTADO_COMPARENDO(1), //
    POLCA(1), //
    CODIGO_INFRACCION(5), //
    VALOR_TARIFA_INFRACCION(8), //
    GRADO_ALCOHOLEMIA(8), //
    TIPO_COMPARENDO(1), //
    FECHA_NOTIFICACION(10), //

    ;

    private int longitud;

    EnumCampoArchivoSimit(int longitud) {
        this.longitud = longitud;
    }

    public int getLongitud() {
        return longitud;
    }

}
