package co.com.datatools.c2.enumeracion;

import co.com.datatools.c2.util.SearchableEnumeration;

/**
 * Definicion de los codigos constantes de los parametros.<br/>
 * Ver Tabla Parametro, documento "catalogos_nuevos.xlsx"
 * 
 * @author NN
 * 
 */
public enum EnumParametro implements SearchableEnumeration<Integer> {

    RAIZ_RUTA_ARCHIVOS(-2), //
    PAIS_INSTALACION(-1), //
    RANGO_FECHA_TRAZABILIDAD(1), //
    REPORTAR_SIMIT_PROCESO(2), //
    DAR_BAJA_COMPARENDO(3), //
    CONSULTAR_VENCIMIENTO_PER(4), //
    GENERAR_VOLANTE_CURSO(6), //
    PERMITIR_DESCU_SIN_IMPUG(7), //
    LIQUIDAR_COMPA_NO_REGIS(8), //
    PASO_APERTURA_PROCESO_CONTR(9), //
    CARGUE_ARCHIVO_AUTO_SIMIT(11), //
    MEDIO_BUSQU_ARCHI_SIMIT(12), //
    RUTA_FTP_SIMIT(13), //
    USUARIO_FTP_SIMIT(14), //
    PASS_FTP_SIMIT(15), //
    CORREO_VERIF_RECAU_SIMIT(16), //
    PASS_CORREO_VERIF_SIMIT(17), //
    NUMERO_SOPORTE_PASO(18), //
    CAPTCHA_OBLIGACIONES(19), //
    VOLANTE_COMPA_NO_REGIS(20), //
    NUMERO_SOPORTE_OBLIG(25), //
    VALOR_COMPA_POST_FALLO(26), //
    PLACA_AGENTE(27), //
    OBLIGACIONES_NO_VIGENTES(28), //
    PROCESOS_IMPIDEN_CONSULTA_OBL(29), //
    MAX_NUM_DIAS_CONSULTA_OBL(30), //
    MOSTRAR_CONSULTA_OBL_MAYORES_NUM_DIAS(31), //
    MOSTRAR_CONSULTA_OBL_PROCESO_IMPUG(32), //
    MOSTRAR_CONSULTA_OBL_MORA(33), //
    MOSTRAR_CONSULTA_OBL_CANCELADA(34), //
    TERMINO_REINCIDENCIA(38), //
    APLICAR_TODAS_INFRAC_REINCIDENCIA(39), //
    ENVIAR_CORREO_REINCIDENCIA(40), //
    REINCIDENCIA_MISMA_INFRACCION(41), //
    GENERA_ALERTA_REINCIDENCIA(42), //
    DIAS_HABILES_GENERA_RESOLUCION(43), //
    TIPO_CONFIG_GEN_ACTO_ADMINISTRATIVO(44), //
    TIPO_CONSEC_RESOLUCION_COMPARENDO(45), //
    CICLO_CONSEC_RESOLUCION_COMPARENDO(46), //
    PROTOCOLO_MENSAJERIA_SIMIT(47), //
    HOST_REMOTO_MAIL_SIMIT(48), //
    RUTA_LOCAL_FTP_SIMIT(49), //
    RUTA_LOCAL_MAIL_SIMIT(50), //
    RUTA_LOCAL_PROCESADOS_SIMIT(51), //
    FORMATO_NOMBRE_ARCHIVO_SIMIT(52), //
    DIAS_ADICIONAL_FECHA_IMPOSICION(57), //
    ACTIVIDADES_AFECTA_CARTERA_CONTRAVENCIONAL(58), //
    DIAS_BUSCAR_COMPARENDO_GEN_RESOL_AUTO(60), //
    PASOS_PREVIOS_IMPOSICION_COMPARENDO(61), //
    REPORTAR_PAGO_SIMIT(62), //
    CRON_GENERAR_CARTE_COMPA(65), //
    REPORTAR_COMPARENDO_SIMIT(67), //
    CAMPOS_NO_MODIF_COMPARENDO(68), //
    VERIFICAR_FALLECIMIENTO_INFRACTOR(69), //
    PORCENTAJE_COINCIDENCIA_NOMBRES(70), //
    CAMPO_ENCABEZADO_ARCH_SIMIT(73), //
    CORREO_NOTIFICA_SIMIT(74), //
    TIPO_ALMACEN_IMG_COMPA(75), //
    RUTA_PRINCIPAL_ALMACEN_IMG_COMPA(76), //
    TIPO_FORMATO_IMG_COMPA(77), //
    FORMATO_CARPETA_ALMACEN_IMG_COMPA(78), //
    TIPO_ALMACEN_FOTO_COMPA(79), //
    RUTA_PRINCIPAL_ALMACEN_FOTO_COMPA(80), //
    TIPO_FORMATO_FOTO_COMPA(81), //
    FORMATO_CARPETA_ALMACEN_FOTO_COMPA(82), //
    TIPO_ALMACEN_PRUEBA_ALCOHOLEMIA(84), //
    RUTA_PRINCIPAL_ALMACEN_PRUEBA_ALCOHOLEMIA(85), //
    TIPO_FORMATO_PRUEBA_ALCOHOLEMIA(86), //
    FORMATO_CARPETA_ALMACEN_PRUEBA_ALCOHOLEMIA(87), //
    CARGUE_ARCH_AUTO_ASOBAN(92), //
    MEDIO_BUSQ_ARCH_ASOBAN(93), //
    RUTA_FTP_ASOBAN(94), //
    USUARIO_FTP_ASOBAN(95), //
    PASS_FTP_ASOBAN(96), //
    CORREO_VERIF_RECAU_ASOBAN(97), //
    PASS_CORREO_VERIF_ASOBAN(98), //
    PROTOCOLO_DESCARGA_ASOBAN(99), //
    HOST_REMOTO_MAIL_ASOBAN(100), //
    RUTA_LOCAL_FTP_ASOBAN(102), //
    RUTA_LOCAL_MAIL_ASOBAN(103), //
    RUTA_LOCAL_MANUAL_ASOBAN(104), //
    RUTA_LOCAL_PROCESADOS_ASOBAN(105), //
    FORMATO_NOMBRE_ARCH_ASOBAN(106), //
    CORREO_NOTIF_ASOBAN(108), //
    MONTO_MIN_CARTERA_COMPA_VIGENTE(111), //
    CRON_GENERAR_ACTOS_ADMIN(112), //
    TIPO_ALMACEN_PROCESA_EVIDENCIA(114), //
    MAX_DIAS_CONSULTA_RESOLUCION(115), //
    RUTA_PRINCIPAL_ALMACEN_PROCESA_EVIDENCIA(116), //
    RECAUDA_PAGOS_OTRAS_ENTIDADES(117), //
    TIPO_DOC_REQ_HUELLA(121), //
    TIPO_DOC_REQ_FOTO(122), //
    DIAS_VIGENCIA_FOTO(123), //
    CRON_REPORTE_INFRACTORES(124), //
    TIPO_SERVICIO_DEFECTO_LIQU_COMP(125), //
    CAMBIAR_INFRACTOR_CURSO(126), //
    ENVIAR_CORREO_INFRACTOR(127), //
    CRON_CIERRE_CONTABLE(128), //
    TOPE_MINIMO_DINERO_DEVOLUCIONES(129), //
    CRON_CONCILIACION_CIERRE(130), //
    URL_DROOLS(131), //
    TIPO_RESOLUCION_FALLO_CONTRA(132), //
    PRIORIDAD_BUSQUEDA_PERSONA(133), //
    MAX_ADJUNTAR_ARCHIVO(134), //
    PAGAR_OBLIGACION_MAS_ANTIGUA_SALDO_FAVOR(135), //
    MAX_RANGO_DIAS_REPORTE_SOLICITUD(136), //
    CONCEPTO_INTERESES(138), //
    CODIGO_POLCA(140), //
    MAX_DIAS_CONSULTA_COMPARENDOS(142), //
    NOMBRE_POLCA(143), //
    SUFIJO_ACTA_CONTROL(144), //
    SUFIJO_PAPELETA(145), //
    REQUIERE_PLACA_AGENTE(146), //
    RUTA_ALMACEN_PROCESA_EVIDENCIA(147), //
    DEUDOR_SIN_INFRACTOR(148), //
    MAX_DIAS_CONSULTA(150), //
    MAX_REGS_COMP_SIMIT(151), //
    ARCH_SIMIT_INCLUYE_CERO(152), //
    NOMBRE_ARCH_COMPA_SIMIT(153), //
    EXT_ARCH_COMPA_SIMIT(154), //
    SEP_ARCH_COMPA_SIMIT(155), //
    CRON_GENERAR_ARCHIVO_COMPA_SIMIT(156), //
    CANT_MEDIA_DIAS_REALIZAR_CONSULTA(157), //
    MIN_DIAS_CONSULTA_GENERAL(142), //
    MAX_CANT_RECTIFICAR_COMPA(159), //
    DIAS_GENERACION_AVISO_NOTIF(160), //
    DIAS_ACTIVAR_CARTE_AVISO(161), //
    TIPO_DIA_NOTIF(162), //
    CRON_GENERAR_RESOL_SANC(164), //
    VALOR_MAX_COMPA_SIMIT(168), //
    ORGANISMO_TRANSITO_MANEJA_POLCA(169), //
    ORGANISMO_LIQUIDA(170), //
    PERIODICIDAD_ENVIO_INCONSISTENCIAS_COMPARENDOS(171), //
    PERIODICIDAD_GENERACION_INCONSISTENCIAS_RECAUDO(172), //
    PERIODICIDAD_SOLICITUD_DATOS_RECAUDO_TERCEROS(173), //
    PERIODICIDAD_GENERACION_RECEPCION_DATOS_RECAUDO(174), //
    PERIODICIDAD_SOLICITUD_DATOS_COMPARENDOS_TERCEROS(175), //
    MAX_INTENTOS_CONCILIAR_PAGO(176), //
    REGISTRAR_OBLIGACION_SAC(177), //
    PERIODICIDAD_REPLICAR_NOVEDADES_SAC(178), //
    PERIODICIDAD_REPLICAR_UBICABILIDAD_SAC(179), //
    PERIODICIDAD_SOLICITUD_UBICABILIDAD_TERCEROS(180), //
    PERIODICIDAD_REPORTE_CONCILIACION_RECAUDO(181), //
    PERIODICIDAD_VALIDAR_CONCILIACION(182), //
    PERIODICIDAD_REPLICAR_FINANCIACIONES(183), //
    PERIODICIDAD_RECIBIR_GESTION_COBRO(184), //
    PERIODICIDAD_ACTUALIZAR_GESTION(185), //
    PERMITIR_REGISTROS_REPETIDOS_UBICABILIDAD(186), //
    DIAS_COBRO_COMPARENDO_PEDESTRE(187), //
    PERIODICIDAD_ACTUALIZAR_OBLIGACION_FINANCIADA(188), //
    DIAS_BUSCAR_OBLIGACIONES_SAC(189), //
    DIAS_IMPUGAR(191), //
    CANT_DIAS_MIN_SOLICI_ACT_UBICABILIDAD(192), //
    CANT_DIAS_PERMITIR_PAGO_CUOTA_INICIAL(193), //
    CANT_VECES_PERMITIR_PRORROGA(194), //
    DIAS_MAX_CIERRE_PROCESO_IMPUGNA(195), //
    DIAS_HABILES_ESPERA_PRUEBAS(196), //
    PERIODICIDAD_CIERRE_PRUEBAS_IMPUGNACION(197), //
    NUM_MAX_DIAS_CONSULTA_ANULACION(198), //
    PERIODICIDAD_VALIDACION_FINANCIACION_PENDIENTE(199), //
    CANT_DIAS_ESPERA_REPORTE_PAGO_TERCERO(200), //
    PERIODICIDAD_ABRIR_PROCESO_COACTIVO_OBLIGACIONES(202), //
    REPLICAR_COMPARENDOS_SAC(203), //
    REPLICAR_FINANCIACION_SAC(204), //
    REGISTRAR_FINANCIACION_TERCEROS(205), //
    CAPT_INFO_PERSONA_BIOMETRICO(206), //
    FORMATO_MONEDA(207), //
    FORMATO_FECHA(208), //
    REPLICAR_NOVEDADES_IMPUGNACION_SAC(209), //
    REPLICAR_NOVEDADES_ANULACION_SAC(210), //
    REPLICAR_NOVEDADES_PAGOS_SAC(211), //
    REGISTRAR_IMPUGNACION_TERCEROS(212), //
    REGISTRAR_ANULACION_SOLICITUDES_FINANCIACION(213), //
    REGISTRAR_FINANCIACIONES_INCUMPLIDAS_COACTIVO(214), //
    PERIODICIDAD_ABRIR_PROCESO_VALIDAR_AGENTE(215), //
    REGISTRAR_ENVIO_CORREO_VALIDAR_AGENTE(216), //
    INSERTAR_COMPARENDO_AGENTE(217), //
    DIAS_CONSULTA_COMPARENDOS_SIN_AGENTE_VALIDO(218), //
    PERIODICIDAD_ENVIO_COMPARENDOS_E_NOTIFICA(219), //
    URL_EVIDENCIAS(220), //
    PERIODICIDAD_CONSULTA_CIRCUITO_E_NOTIFICA(221), //
    REGISTRAR_COACTIVO_TERCEROS(222), //
    ENVIO_NOTIFICACION_POR_TERCERO(223), //
    NUM_MAX_LINEAS_CARGUE_ARCHIVO(224), //
    GENERAR_DOC_NOTIFI_PROCESO_COACTIVO(225), //
    NUM_MAX_LINEAS_CARGUE_COACTIVO(226), //
    CIERRE_CARGUES_ERRONEOS(227), //
    PLAZO_RADICAR_EXCEPCIONES(228), //
    TIPO_DIA(229), //
    DIAS_NUEVO_PLAZO_PAGO(30),//
    ;

    private int codigo;

    EnumParametro(int codigo) {
        this.codigo = codigo;
    }

    public int getCodigo() {
        return codigo;
    }

    @Override
    public Integer getValue() {
        return codigo;
    }
}
