package co.com.datatools.c2.enumeracion;

import co.com.datatools.c2.util.SearchableEnumeration;

/**
 * Enumeracion que permite identificar los campos de una determinada entidad con su respectivo codigo
 * 
 * @author luis.forero(2016-02-03)
 */

/**
 * 
 * Se realiza asociacion de enumeracion para el formulario de procesa comparendo.
 * 
 * @author javier.fajardo(2016-04-12)
 */

public enum EnumCampoEntidad implements SearchableEnumeration<Integer> {

    ACTIVO_PCC(64, EnumEntidad.PROCESA_COMPARENDO), ORGANISMO_TRANSITO_PCC(2,
            EnumEntidad.PROCESA_COMPARENDO), CATEGORIA_LICENCIA_CONDUCCION_INFRACTOR_PCC(71,
                    EnumEntidad.PROCESA_COMPARENDO), TIPO_COMPARENDO_PCC(3, EnumEntidad.PROCESA_COMPARENDO), //
    CLASE_VEHICULO_PCC(32, EnumEntidad.PROCESA_COMPARENDO), //
    COLOR_PCC(38, EnumEntidad.PROCESA_COMPARENDO), //
    CONSECUTIVO_INMOVILIZACION_PCC(57, EnumEntidad.PROCESA_COMPARENDO), // )
    CODIGO_ORIGEN_COMPARENDO_PCC(5, EnumEntidad.PROCESA_COMPARENDO), // )
    CODIGO_ORG_TRANS_LICENCIA_PCC(79, EnumEntidad.PROCESA_COMPARENDO), // )
    DIRECCION_PROPIETARIO_PCC(89, EnumEntidad.PROCESA_COMPARENDO), // )
    DIRECCION_EMPRESA_PCC(93, EnumEntidad.PROCESA_COMPARENDO), //
    DIRECCION_COMPARENDO_PCC(11, EnumEntidad.PROCESA_COMPARENDO), //
    DIRECCION_INFRACTOR_PCC(78, EnumEntidad.PROCESA_COMPARENDO), //
    DIRECCION_TESTIGO_PCC(102, EnumEntidad.PROCESA_COMPARENDO), //
    DIRECCION_PATIO_PCC(109, EnumEntidad.PROCESA_COMPARENDO), //
    DIGITO_VERIFICACION_NIT_PCC(67, EnumEntidad.PROCESA_COMPARENDO), //
    EDAD_INFRACTOR_PCC(77, EnumEntidad.PROCESA_COMPARENDO), //
    EMAIL_INFRACTOR_PCC(80, EnumEntidad.PROCESA_COMPARENDO), //
    ES_POLCA_PCC(106, EnumEntidad.PROCESA_COMPARENDO), //
    EVIDENCIA_PCC(107, EnumEntidad.PROCESA_COMPARENDO), //
    EXISTE_FUGA_INFRACTOR_PCC(14, EnumEntidad.PROCESA_COMPARENDO), //
    FECHA_CORRECCION_PCC(62, EnumEntidad.PROCESA_COMPARENDO), //
    FECHA_EXPEDICION_LICENCIA_CONDUC_INFRAC_PCC(69, EnumEntidad.PROCESA_COMPARENDO), //
    FECHA_INFRACCION_PCC(9, EnumEntidad.PROCESA_COMPARENDO), //
    FECHA_NOTIFICACION_PCC(21, EnumEntidad.PROCESA_COMPARENDO), //
    FECHA_OPERACION_PCC(4, EnumEntidad.PROCESA_COMPARENDO), //
    FECHA_PRUEBA_ALCOHOLEMIA_PCC(19, EnumEntidad.PROCESA_COMPARENDO), //
    FECHA_RECEPCION_PCC(61, EnumEntidad.PROCESA_COMPARENDO), //
    FECHA_VENCIMIENTO_LICENCIA_CONDUC_INFRAC_PCC(70, EnumEntidad.PROCESA_COMPARENDO), //
    GRADO_ALCOHOLEMIA_PCC(17, EnumEntidad.PROCESA_COMPARENDO), //
    HORA_INFRACCION_PCC(10, EnumEntidad.PROCESA_COMPARENDO), //
    IDENTIFICACION_VEHICULO_PCC(30, EnumEntidad.PROCESA_COMPARENDO), //
    INFRACCION_PCC(12, EnumEntidad.PROCESA_COMPARENDO), //
    INMOVILIZADO_PCC(23, EnumEntidad.PROCESA_COMPARENDO), //
    LICENCIA_TRANSITO_PCC(35, EnumEntidad.PROCESA_COMPARENDO), //
    LINEA_VEHICULO_PCC(37, EnumEntidad.PROCESA_COMPARENDO), //
    MARCA_VEHICULO_PCC(36, EnumEntidad.PROCESA_COMPARENDO), //
    MEDIO_IMPOSICION_PCC(6, EnumEntidad.PROCESA_COMPARENDO), //
    MODALIDAD_PCC(28, EnumEntidad.PROCESA_COMPARENDO), //
    MODELO_PCC(40, EnumEntidad.PROCESA_COMPARENDO), //
    NIEGA_PRUEBA_ALCOHOLEMIA_PCC(15, EnumEntidad.PROCESA_COMPARENDO), //
    NIVEL_SERVICIO_PCC(33, EnumEntidad.PROCESA_COMPARENDO), //
    NOMBRE_PATIO_PCC(59, EnumEntidad.PROCESA_COMPARENDO), //
    NOMBRE_RESPONSABLE_PCC(49, EnumEntidad.PROCESA_COMPARENDO), //
    NUMERO_REINCIDENCIA_PCC(20, EnumEntidad.PROCESA_COMPARENDO), //
    NUMERO_COMPARENDO_PCC(1, EnumEntidad.PROCESA_COMPARENDO), //
    NUMERO_FACTURA_PCC(228, EnumEntidad.PROCESA_COMPARENDO), //
    NUMERO_CITACION_PCC(227, EnumEntidad.PROCESA_COMPARENDO), //
    NUMERO_DOCUMENTO_PROPIETARIO_PCC(84, EnumEntidad.PROCESA_COMPARENDO), //
    NUMERO_DOCUMENTO_TESTIGO_PCC(97, EnumEntidad.PROCESA_COMPARENDO), //
    NUMERO_DOCUMENTO_INFRACTOR_PCC(66, EnumEntidad.PROCESA_COMPARENDO), // ok
    NUMERO_DOCUMENTO_EMPRESA_PCC(92, EnumEntidad.PROCESA_COMPARENDO), //
    NUMERO_GRUA_PCC(55, EnumEntidad.PROCESA_COMPARENDO), //
    NUMERO_IDENTIFICACION_AGENTE_PCC(47, EnumEntidad.PROCESA_COMPARENDO), //
    NUMERO_INFORME_PCC(60, EnumEntidad.PROCESA_COMPARENDO), //
    NUMERO_LICENCIA_CONDUCCION_INFRACTOR_PCC(68, EnumEntidad.PROCESA_COMPARENDO), //
    NUMERO_MOTOR_PCC(39, EnumEntidad.PROCESA_COMPARENDO), //
    NUMERO_PATIO_PCC(54, EnumEntidad.PROCESA_COMPARENDO), //
    NUMERO_PRUEBA_ALCOHOLEMIA_PCC(16, EnumEntidad.PROCESA_COMPARENDO), //
    NUMERO_TARJETA_OPERACION_PCC(31, EnumEntidad.PROCESA_COMPARENDO), //
    OBSERVACIONES_AGENTE_PCC(45, EnumEntidad.PROCESA_COMPARENDO), //
    OBSERVACIONES_INFRACTOR_PCC(22, EnumEntidad.PROCESA_COMPARENDO), //
    ORGANISMO_LICENCIA_TRANSITO_PCC(105, EnumEntidad.PROCESA_COMPARENDO), //
    ORGANISMO_MATRICULA_VEHICULO_PCC(34, EnumEntidad.PROCESA_COMPARENDO), //
    PATIO_PCC(54, EnumEntidad.PROCESA_COMPARENDO), //
    PESO_NETO_PCC(43, EnumEntidad.PROCESA_COMPARENDO), //
    PESO_SECO_PCC(42, EnumEntidad.PROCESA_COMPARENDO), //
    PLACA_AGENTE_PCC(41, EnumEntidad.PROCESA_COMPARENDO), //
    PLACA_GRUA_PCC(56, EnumEntidad.PROCESA_COMPARENDO), //
    PLACA_VEHICULO_PCC(29, EnumEntidad.PROCESA_COMPARENDO), //
    PRIMER_APELLIDO_AGENTE_PCC(50, EnumEntidad.PROCESA_COMPARENDO), //
    PRIMER_APELLIDO_INFRACTOR_PCC(72, EnumEntidad.PROCESA_COMPARENDO), //
    PRIMER_APELLIDO_PROPIETARIO_PCC(85, EnumEntidad.PROCESA_COMPARENDO), //
    PRIMER_APELLIDO_TESTIGO_PCC(98, EnumEntidad.PROCESA_COMPARENDO), //
    PRIMER_NOMBRE_AGENTE_PCC(52, EnumEntidad.PROCESA_COMPARENDO), //
    PRIMER_NOMBRE_TESTIGO_PCC(100, EnumEntidad.PROCESA_COMPARENDO), //
    PRIMER_NOMBRE_INFRACTOR_PCC(74, EnumEntidad.PROCESA_COMPARENDO), //
    PRIMER_NOMBRE_PROPIETARIO_PCC(87, EnumEntidad.PROCESA_COMPARENDO), //
    RADIO_ACCION_PCC(27, EnumEntidad.PROCESA_COMPARENDO), //
    RAZON_SOCIAL_INFRACTOR_PCC(76, EnumEntidad.PROCESA_COMPARENDO), //
    RAZON_SOCIAL_EMPRESA_PCC(90, EnumEntidad.PROCESA_COMPARENDO), //
    RETIENE_LICENCIA_PCC(13, EnumEntidad.PROCESA_COMPARENDO), //
    RUTA_PCC(25, EnumEntidad.PROCESA_COMPARENDO), //
    SEGUNDO_APELLIDO_AGENTE_PCC(51, EnumEntidad.PROCESA_COMPARENDO), //
    SEGUNDO_APELLIDO_INFRACTOR_PCC(73, EnumEntidad.PROCESA_COMPARENDO), //
    SEGUNDO_APELLIDO_PROPIETARIO_PCC(86, EnumEntidad.PROCESA_COMPARENDO), //
    SEGUNDO_APELLIDO_TESTIGO_PCC(99, EnumEntidad.PROCESA_COMPARENDO), //
    SEGUNDO_NOMBRE_AGENTE_PCC(53, EnumEntidad.PROCESA_COMPARENDO), //
    SEGUNDO_NOMBRE_INFRACTOR_PCC(75, EnumEntidad.PROCESA_COMPARENDO), //
    SEGUNDO_NOMBRE_PROPIETARIO_PCC(88, EnumEntidad.PROCESA_COMPARENDO), //
    SEGUNDO_NOMBRE_TESTIGO_PCC(101, EnumEntidad.PROCESA_COMPARENDO), //
    TELEFONO_FIJO_EMPRESA_PCC(94, EnumEntidad.PROCESA_COMPARENDO), //
    TELEFONO_FIJO_INFRACTOR_PCC(81, EnumEntidad.PROCESA_COMPARENDO), //
    TELEFONO_FIJO_TESTIGO_PCC(103, EnumEntidad.PROCESA_COMPARENDO), //
    TELEFONO_MOVIL_EMPRESA_PCC(95, EnumEntidad.PROCESA_COMPARENDO), //
    TELEFONO_MOVIL_INFRACTOR_PCC(82, EnumEntidad.PROCESA_COMPARENDO), //
    TELEFONO_MOVIL_TESTIGO_PCC(104, EnumEntidad.PROCESA_COMPARENDO), //
    TIPO_DOCUMENTO_TESTIGO_PCC(96, EnumEntidad.PROCESA_COMPARENDO), //
    TIPO_DOCUMENTO_INFRACTOR_PCC(65, EnumEntidad.PROCESA_COMPARENDO), //
    TIPO_DOCUMENTO_PROPIETARIO_PCC(83, EnumEntidad.PROCESA_COMPARENDO), //
    TIPO_DOCUMENTO_EMPRESA_PCC(91, EnumEntidad.PROCESA_COMPARENDO), //
    TIPO_IDENTIFICACION_AGENTE_PCC(46, EnumEntidad.PROCESA_COMPARENDO), //
    TIPO_INFRACTOR_PCC(7, EnumEntidad.PROCESA_COMPARENDO), //
    TIPO_NOTIFICACION_PCC(8, EnumEntidad.PROCESA_COMPARENDO), //
    TIPO_SERVICIO_PCC(26, EnumEntidad.PROCESA_COMPARENDO), //
    TIPO_TRANSPORTE_PASAJEROS_PCC(108, EnumEntidad.PROCESA_COMPARENDO), //
    UNIFICACION_RESPONSABLE_PCC(48, EnumEntidad.PROCESA_COMPARENDO), //
    USUARIO_PCC(24, EnumEntidad.PROCESA_COMPARENDO), //
    VALOR_GRADO_ALCOHOLEMIA_PCC(18, EnumEntidad.PROCESA_COMPARENDO), //
    AGENTE_TRANSITO_PCC(44, EnumEntidad.PROCESA_COMPARENDO), //
    PAIS_DIRECCION_PCC(220, EnumEntidad.PROCESA_COMPARENDO), //
    DEPARTAMENTO_DIRECCION_PCC(221, EnumEntidad.PROCESA_COMPARENDO), //
    MUNICIPIO_DIRECCION_PCC(222, EnumEntidad.PROCESA_COMPARENDO), //
    LOCALIDAD_DIRECCION_PCC(223, EnumEntidad.PROCESA_COMPARENDO), //
    ESTADO_COMPARENDO_PCC(224, EnumEntidad.PROCESA_COMPARENDO), //
    TIPO_EVIDENCIA_PCC(225, EnumEntidad.PROCESA_COMPARENDO), //
    NO_ES_CAMPO_PCC(226, EnumEntidad.PROCESA_COMPARENDO), //

    // ////////////////////

    FECHA_REGISTRO(110, EnumEntidad.COMPARENDO), //
    FECHA_MODIFICACION(111, EnumEntidad.COMPARENDO), //
    ESTADO_COMPARENDO(112, EnumEntidad.COMPARENDO), //
    TIPO_COMPARENDO(113, EnumEntidad.COMPARENDO), //
    ORIGEN_COMPARENDO(114, EnumEntidad.COMPARENDO), //
    MEDIO_IMPOSICION(115, EnumEntidad.COMPARENDO), //
    TIPO_INFRACTOR(116, EnumEntidad.COMPARENDO), //
    TIPO_NOTIFICACION(117, EnumEntidad.COMPARENDO), //
    FECHA_INFRACCION(118, EnumEntidad.COMPARENDO), //
    HORA_INFRACCION(119, EnumEntidad.COMPARENDO), //
    DIRECCION_COMPARENDO(120, EnumEntidad.COMPARENDO), //
    INFRACCION(121, EnumEntidad.COMPARENDO), //
    RETIENE_LICENCIA(122, EnumEntidad.COMPARENDO), //
    EXISTE_FUGA_INFRACTOR(123, EnumEntidad.COMPARENDO), //
    NIEGA_PRUEBA_ALCOHOLEMIA(124, EnumEntidad.COMPARENDO), //
    NUMERO_PRUEBA_ALCOHOLEMIA(125, EnumEntidad.COMPARENDO), //
    GRADO_ALCOHOLEMIA(126, EnumEntidad.COMPARENDO), //
    VALOR_GRADO_ALCOHOLEMIA(127, EnumEntidad.COMPARENDO), //
    FECHA_PRUEBA_ALCOHOLEMIA(128, EnumEntidad.COMPARENDO), //
    NUMERO_REINCIDENCIAS(129, EnumEntidad.COMPARENDO), //
    FECHA_NOTIFICACION(130, EnumEntidad.COMPARENDO), //
    OBSERVACIONES_INFRACTOR(131, EnumEntidad.COMPARENDO), //
    USUARIO(132, EnumEntidad.COMPARENDO), //
    RUTA(133, EnumEntidad.COMPARENDO), //
    FECHA_GENERACION_CARTERA(134, EnumEntidad.COMPARENDO), //
    CARTERA_GENERADA(135, EnumEntidad.COMPARENDO), //
    ES_POLCA(136, EnumEntidad.COMPARENDO), //
    ESTADO_COMPARENDO_SIMIT(137, EnumEntidad.COMPARENDO), //
    DOCUMENTO_NOTIFICACION(138, EnumEntidad.COMPARENDO), //
    TIPO_SERVICIO(139, EnumEntidad.COMPARENDO), //
    RADIO_ACCION(140, EnumEntidad.COMPARENDO), //
    MODALIDAD(141, EnumEntidad.COMPARENDO), //
    PLACA_VEHICULO(142, EnumEntidad.COMPARENDO), //
    IDENTIFICACION_VEHICULO(143, EnumEntidad.COMPARENDO), //
    NUMERO_TARJETA_OPERACION(144, EnumEntidad.COMPARENDO), //
    CLASE_VEHICULO(145, EnumEntidad.COMPARENDO), //
    NIVEL_SERVICIO(146, EnumEntidad.COMPARENDO), //
    ORGANISMO_MATRICULA_VEHICULO(147, EnumEntidad.COMPARENDO), //
    ORGANISMO_LICENCIA_TRANSITO(148, EnumEntidad.COMPARENDO), //
    NUMERO_LICENCIA_TRANSITO(149, EnumEntidad.COMPARENDO), //
    MARCA_VEHICULO(150, EnumEntidad.COMPARENDO), //
    LINEA_VEHICULO(151, EnumEntidad.COMPARENDO), //
    COLOR(152, EnumEntidad.COMPARENDO), //
    NUMERO_MOTOR(153, EnumEntidad.COMPARENDO), //
    MODELO(154, EnumEntidad.COMPARENDO), //
    PESO_SECO(155, EnumEntidad.COMPARENDO), //
    PESO_NETO(156, EnumEntidad.COMPARENDO), //
    TIPO_TRANSPORTE_PASAJEROS(157, EnumEntidad.COMPARENDO), //
    TIPO_IDENTIFICACION_AGENTE(158, EnumEntidad.COMPARENDO), //
    NUMERO_IDENTIFICACION_AGENTE(159, EnumEntidad.COMPARENDO), //
    PLACA_AGENTE(160, EnumEntidad.COMPARENDO), //
    PRIMER_APELLIDO_AGENTE(161, EnumEntidad.COMPARENDO), //
    SEGUNDO_APELLIDO_AGENTE(162, EnumEntidad.COMPARENDO), //
    PRIMER_NOMBRE_AGENTE(163, EnumEntidad.COMPARENDO), //
    SEGUNDO_NOMBRE_AGENTE(164, EnumEntidad.COMPARENDO), //
    UNIFICACION_RESPONSABLE(165, EnumEntidad.COMPARENDO), //
    NOMBRE_RESPONSABLE(166, EnumEntidad.COMPARENDO), //
    AGENTE_TRANSITO(167, EnumEntidad.COMPARENDO), //
    OBSERVACIONES_AGENTE(168, EnumEntidad.COMPARENDO), //
    PATIO(169, EnumEntidad.COMPARENDO), //
    NUMERO_PATIO(170, EnumEntidad.COMPARENDO), //
    NOMBRE_PATIO(171, EnumEntidad.COMPARENDO), //
    NUMERO_GRUA(172, EnumEntidad.COMPARENDO), //
    PLACA_GRUA(173, EnumEntidad.COMPARENDO), //
    CONSECUTIVO_INMOVILIZACION(174, EnumEntidad.COMPARENDO), //
    NUMERO_INFORME(175, EnumEntidad.COMPARENDO), //
    DIRECCION_PATIO(176, EnumEntidad.COMPARENDO), //
    PERSONA_INFRACTOR(177, EnumEntidad.COMPARENDO), //
    TIPO_DOCUMENTO_INFRACTOR(178, EnumEntidad.COMPARENDO), //
    NUMERO_DOCUMENTO_INFRACTOR(179, EnumEntidad.COMPARENDO), //
    DIGITO_VERIFICACION_INFRACTOR(180, EnumEntidad.COMPARENDO), //
    LICENCIA_INFRACTOR(181, EnumEntidad.COMPARENDO), //
    CODIGO_ORG_TRANS_LICENCIA_INFRACTOR(182, EnumEntidad.COMPARENDO), //
    NUMERO_LICENCIA_CONDUCCION_INFRACTOR(183, EnumEntidad.COMPARENDO), //
    CATEGORIA_LICENCIA_CONDUCCIÓN_INFRACTOR(184, EnumEntidad.COMPARENDO), //
    FECHA_EXPEDICION_LICENCIA_CONDUC_INFRAC(185, EnumEntidad.COMPARENDO), //
    FECHA_VENCIMIENTO_LICENCIA_CONDUC_INFRAC(186, EnumEntidad.COMPARENDO), //
    PRIMER_APELLIDO_INFRACTOR(187, EnumEntidad.COMPARENDO), //
    SEGUNDO_APELLIDO_INFRACTOR(188, EnumEntidad.COMPARENDO), //
    PRIMER_NOMBRE_INFRACTOR(189, EnumEntidad.COMPARENDO), //
    SEGUNDO_NOMBRE_INFRACTOR(190, EnumEntidad.COMPARENDO), //
    RAZON_SOCIAL_INFRACTOR(191, EnumEntidad.COMPARENDO), //
    EDAD_INFRACTOR(192, EnumEntidad.COMPARENDO), //
    DIRECCION_INFRACTOR(193, EnumEntidad.COMPARENDO), //
    EMAIL_INFRACTOR(194, EnumEntidad.COMPARENDO), //
    TELEFONO_FIJO_INFRACTOR(195, EnumEntidad.COMPARENDO), //
    TELEFONO_MOVIL_INFRACTOR(196, EnumEntidad.COMPARENDO), //
    FECHA_INICIO_INFRACTOR(197, EnumEntidad.COMPARENDO), //
    FECHA_FIN_INFRACTOR(198, EnumEntidad.COMPARENDO), //
    TIPO_DOCUMENTO_PROPIETARIO(199, EnumEntidad.COMPARENDO), //
    NUMERO_DOCUMENTO_PROPIETARIO(200, EnumEntidad.COMPARENDO), //
    PRIMER_APELLIDO_PROPIETARIO(201, EnumEntidad.COMPARENDO), //
    SEGUNDO_APELLIDO_PROPIETARIO(202, EnumEntidad.COMPARENDO), //
    PRIMER_NOMBRE_PROPIETARIO(203, EnumEntidad.COMPARENDO), //
    SEGUNDO_NOMBRE_PROPIETARIO(204, EnumEntidad.COMPARENDO), //
    TIPO_DOCUMENTO_TESTIGO(205, EnumEntidad.COMPARENDO), //
    NUMERO_DOCUMENTO_TESTIGO(206, EnumEntidad.COMPARENDO), //
    PRIMER_APELLIDO_TESTIGO(207, EnumEntidad.COMPARENDO), //
    SEGUNDO_APELLIDO_TESTIGO(208, EnumEntidad.COMPARENDO), //
    PRIMER_NOMBRE_TESTIGO(209, EnumEntidad.COMPARENDO), //
    SEGUNDO_NOMBRE_TESTIGO(210, EnumEntidad.COMPARENDO), //
    TELEFONO_MOVIL_TESTIGO(211, EnumEntidad.COMPARENDO), //
    DIRECCION_TESTIGO(212, EnumEntidad.COMPARENDO), //
    RAZON_SOCIAL_EMPRESA(213, EnumEntidad.COMPARENDO), //
    TIPO_DOCUMENTO_EMPRESA(214, EnumEntidad.COMPARENDO), //
    NUMERO_DOCUMENTO_EMPRESA(215, EnumEntidad.COMPARENDO), //
    DIRECCION_EMPRESA(216, EnumEntidad.COMPARENDO), //
    TELEFONO_FIJO_EMPRESA(217, EnumEntidad.COMPARENDO), //
    TELEFONO_MOVIL_EMPRESA(218, EnumEntidad.COMPARENDO), //
    TIPO_AGENTE_IMPOSITOR(219, EnumEntidad.COMPARENDO), //
    ;
    private Integer codigoCampo;
    private EnumEntidad entidad;

    private EnumCampoEntidad(Integer codigoCampo, EnumEntidad entidad) {
        this.codigoCampo = codigoCampo;
        this.entidad = entidad;
    }

    @Override
    public Integer getValue() {
        return codigoCampo;
    }

    /**
     * @return Retorna la entidad a la cual pertenece el campo
     * @author luis.forero (2016-02-03)
     */
    public EnumEntidad getEntidad() {
        return entidad;
    }
}
