package co.com.datatools.c2.enumeracion;

/**
 * Enumeración que representa los tipos de respuesta de procesamiento de los archivos de recaudo SIMIT. Su contenido debe corresponder a la tabla
 * tipo_respuesta_procesamiento
 * 
 * @author robert.bautista
 * 
 */
public enum EnumTipoRespuestaProcesamiento {
    LA_LONGITUD_DEL_ENCABEZADO_NO_ES_CORRECTA(1), //
    EL_CAMPO_DE_CEROS_DEL_ENCABEZADO_NO_ES_CORRECTO(2), //
    EL_CAMPO_ENTIDAD_DEL_ENCABEZADO_NO_ES_CORRECTO(3), //
    EL_CAMPO_CODIGO_BANCO_OFICINA_DEL_ENCABEZADO_NO_ES_CORRECTO(4), //
    LA_LONGITUD_DEL_REGISTRO_DE_PAGO_NO_ES_CORRECTA(5), //
    EL_CAMPO_NUMERO_DE_COMPARENDO_NO_ES_CORRECTO(6), //
    EL_CAMPO_FECHA_NO_ES_CORRECTO(7), //
    EL_CAMPO_CODIGO_DEL_BANCO_NO_ES_CORRECTO(8), //
    EL_CAMPO_NUMERO_DE_CONSIGNACION_NO_ES_CORRECTO(9), //
    EL_CAMPO_VALOR_NO_ES_CORRECTO(10), //
    EL_CAMPO_NUMERO_DE_DOCUMENTO_NO_ES_CORRECTO(11), //
    LA_LONGITUD_DEL_ARCHIVO_NO_ES_CORRECTA(12), //
    LA_LONGITUD_DEL_PIE_DEL_ARCHIVO_NO_ES_CORRECTA(13), //
    EL_CAMPO_NUEVES_DEL_PIE_NO_ES_CORRECTO(14), //
    EL_NUMERO_DE_PAGOS_DEL_PIE_NO_COINCIDE_CON_EL_NUMERO_DE_PAGOS_REPORTADOS(15), //
    EL_VALOR_DE_PAGOS_DEL_PIE_NO_COINCIDE_CON_EL_VALOR_DE_PAGOS_REPORTADOS(16), //
    REGISTRO_EXITOSO(17), //
    LA_AFECTACION_DE_CARTERA_DEL_COMPARENDO_NO_FUE_EXITOSA(18), //
    EL_REGISTRO_DE_LA_REFERENCIA_DE_PAGO_NO_FUE_EXITOSO(19), //
    LA_GENERACION_DE_LA_REFERENCIA_DE_PAGO_NO_FUE_EXITOSA(20), //
    LA_CONSULTA_DEL_COMPARENDO_NO_FUE_EXITOSA(21), //
    EL_ARCHIVO_FUE_PROCESADO_EXITOSAMENTE(22), //
    EL_ARCHIVO_NO_SE_PROCESO(23), //
    EL_ARCHIVO_POSEE_UNA_ESTRUCTURA_CORRECTA(24), //
    ERROR_DESCONOCIDO(25), //
    NO_EXISTEN_ARCHIVOS_POR_PROCESAR(26), //
    ARCHIVO_FUE_PROCESADO_ANTERIORMENTE(27);

    private int pk;

    EnumTipoRespuestaProcesamiento(int pk) {
        this.pk = pk;
    }

    public int getPk() {
        return pk;
    }

}