SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM trazabilidad_comparendo;
DELETE FROM orden_comparendo_nacional;
DELETE FROM unificacion_responsable;
DELETE FROM responsable_formulario;
DELETE FROM persona WHERE ID_PERSONA <> -1;
DELETE FROM direccion;
DELETE FROM persona_juridica;
DELETE FROM comparendo;
DELETE FROM comparendo_vehiculo;
DELETE FROM comparendo_agente;
DELETE FROM comparendo_patio;
DELETE FROM comparendo_persona;
DELETE FROM agente;
DELETE FROM comparendo_cartera;
DELETE FROM saldo_cartera;
DELETE FROM cartera;
DELETE FROM configuracion_descuento;
DELETE FROM descuento_notificacion;
DELETE FROM descuento_medio_imposicion;
DELETE FROM resolucion;
DELETE FROM comparendo_resolucion;
DELETE FROM infraccion WHERE id_infraccion = -1;
DELETE FROM configuracion_infraccion WHERE id_configuracion_infraccion in (-12,-13);
DELETE FROM tipo_sancion_confi_infra WHERE id_configuracion_infraccion in (-12,-13);