
package co.com.datatools.c2.ws.sac.reportegestion.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.13
 * Fri Apr 22 15:43:02 COT 2016
 * Generated source version: 2.7.13
 */

@XmlRootElement(name = "procesarGestionCobro", namespace = "http://reportegestion.sac.ws.c2.datatools.com.co/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "procesarGestionCobro", namespace = "http://reportegestion.sac.ws.c2.datatools.com.co/")

public class ProcesarGestionCobro {

    @XmlElement(name = "gestionCobroWSDTO")
    private co.com.datatools.c2.dto.ws.GestionCobroWSDTO gestionCobroWSDTO;

    public co.com.datatools.c2.dto.ws.GestionCobroWSDTO getGestionCobroWSDTO() {
        return this.gestionCobroWSDTO;
    }

    public void setGestionCobroWSDTO(co.com.datatools.c2.dto.ws.GestionCobroWSDTO newGestionCobroWSDTO)  {
        this.gestionCobroWSDTO = newGestionCobroWSDTO;
    }

}

