package co.com.datatools.c2.ws.comparendo.recepcion.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.6 Fri Oct 18 17:07:09 COT 2013 Generated source version: 2.4.6
 */

@XmlRootElement(name = "recibirComparendoResponse", namespace = "http://recepcion.comparendo.ws.c2.datatools.com.co/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recibirComparendoResponse", namespace = "http://recepcion.comparendo.ws.c2.datatools.com.co/")
public class RecibirComparendoResponse {

    @XmlElement(name = "return")
    private co.com.datatools.c2.dto.ws.RespuestaRecibirComparendoWSDTO _return;

    public co.com.datatools.c2.dto.ws.RespuestaRecibirComparendoWSDTO getReturn() {
        return this._return;
    }

    public void setReturn(co.com.datatools.c2.dto.ws.RespuestaRecibirComparendoWSDTO new_return) {
        this._return = new_return;
    }

}
