
package co.com.datatools.c2.clientes.ws.simit.carga;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.13
 * 2016-03-28T16:24:10.959-05:00
 * Generated source version: 2.7.13
 */

@WebFault(name = "Exception", targetNamespace = "http://webservices.qxmultas.quipux.com.co")
public class Exception_Exception extends java.lang.Exception {
    
    private co.com.datatools.c2.clientes.ws.simit.carga.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, co.com.datatools.c2.clientes.ws.simit.carga.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, co.com.datatools.c2.clientes.ws.simit.carga.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public co.com.datatools.c2.clientes.ws.simit.carga.Exception getFaultInfo() {
        return this.exception;
    }
}
