
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package co.com.datatools.c2.clientes.ws.simit.carga;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2016-03-28T16:24:10.980-05:00
 * Generated source version: 2.7.13
 * 
 */

@javax.jws.WebService(
                      serviceName = "WsCargaArchivos",
                      portName = "WsCargaArchivosHttpSoap11Endpoint",
                      targetNamespace = "http://webservices.qxmultas.quipux.com.co",
                      wsdlLocation = "http://181.48.11.2:8282/simit-pruebas/services/WsCargaArchivos?wsdl",
                      endpointInterface = "co.com.datatools.c2.simit.ws.cliente.WsCargaArchivosPortType")
                      
public class WsCargaArchivosPortTypeImpl1 implements WsCargaArchivosPortType {

    private static final Logger LOG = Logger.getLogger(WsCargaArchivosPortTypeImpl1.class.getName());

    /* (non-Javadoc)
     * @see co.com.datatools.c2.simit.ws.cliente.WsCargaArchivosPortType#cargaRecaudo(co.com.quipux.qxmultas.webservices.xsd.DatosRecaudo  recaudo )*
     */
    public java.lang.String cargaRecaudo(co.com.datatools.c2.clientes.ws.simit.carga.dto.DatosRecaudo recaudo) throws Exception_Exception    { 
        LOG.info("Executing operation cargaRecaudo");
        System.out.println(recaudo);
        try {
            java.lang.String _return = "_return-456964050";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see co.com.datatools.c2.simit.ws.cliente.WsCargaArchivosPortType#cargaArchivoResolucion(co.com.quipux.qxmultas.webservices.xsd.DatosResolucion  resolucion )*
     */
    public java.lang.String cargaArchivoResolucion(co.com.datatools.c2.clientes.ws.simit.carga.dto.DatosResolucion resolucion) throws Exception_Exception    { 
        LOG.info("Executing operation cargaArchivoResolucion");
        System.out.println(resolucion);
        try {
            java.lang.String _return = "_return561733569";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see co.com.datatools.c2.simit.ws.cliente.WsCargaArchivosPortType#cargaArchivoComparendos(co.com.quipux.qxmultas.webservices.xsd.DatosComparendo  comparendo )*
     */
    public java.lang.String cargaArchivoComparendos(co.com.datatools.c2.clientes.ws.simit.carga.dto.DatosComparendo comparendo) throws Exception_Exception    { 
        LOG.info("Executing operation cargaArchivoComparendos");
        System.out.println(comparendo);
        try {
            java.lang.String _return = "_return-1761302018";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

}
