SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM formulario;
DELETE FROM seguimiento_formulario;
DELETE FROM detalle_cambio_estado;
DELETE FROM rango_formulario;
DELETE FROM detalle_numeracion;
DELETE FROM numeracion_formulario;
DELETE FROM unificacion_responsable;
DELETE FROM stock_tipo_responsable;
DELETE FROM responsable_formulario;
DELETE FROM persona_juridica;