-- 
--  persona
-- 
INSERT INTO persona (ID_PERSONA, ID_TIPO_IDENTIFICACION, NUMERO_IDENTIFICACION, CODIGO_FUENTE_INFORMACION, CODIGO_ORGANISMO, FECHA_ULTIMA_ACTUALIZACION) VALUES ('-2', '1', '10000000001', '18', '11001', '2014-01-01');
-- 
--  usuario_persona
-- 
INSERT INTO usuario_persona (ID_USUARIO, ID_PERSONA, LOGIN) VALUES ('-2', '-2', 'anonymous'); 