package co.com.datatools.c2.ws.recaudo.recepcion.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.13 Thu Apr 21 17:46:49 COT 2016 Generated source version: 2.7.13
 */

@XmlRootElement(name = "replicarPagoResponse", namespace = "http://recepcion.recaudo.ws.c2.datatools.com.co/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "replicarPagoResponse", namespace = "http://recepcion.recaudo.ws.c2.datatools.com.co/")
public class ReplicarPagoResponse {

    @XmlElement(name = "return")
    private co.com.datatools.c2.dto.ws.RespuestaWSDTO _return;

    public co.com.datatools.c2.dto.ws.RespuestaWSDTO getReturn() {
        return this._return;
    }

    public void setReturn(co.com.datatools.c2.dto.ws.RespuestaWSDTO new_return) {
        this._return = new_return;
    }

}
