
package co.com.datatools.poc.cxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.6
 * Fri Apr 17 11:23:44 COT 2015
 * Generated source version: 2.4.6
 */

@XmlRootElement(name = "sumaResponse", namespace = "http://suma.ws.poc.c2.datatools.com.co/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sumaResponse", namespace = "http://suma.ws.poc.c2.datatools.com.co/")

public class SumaResponse {

    @XmlElement(name = "return")
    private int _return;

    public int getReturn() {
        return this._return;
    }

    public void setReturn(int new_return)  {
        this._return = new_return;
    }

}

