-- 
--  persona
-- 
INSERT INTO persona (ID_PERSONA, ID_TIPO_IDENTIFICACION, NUMERO_IDENTIFICACION, CODIGO_FUENTE_INFORMACION, CODIGO_ORGANISMO, FECHA_ULTIMA_ACTUALIZACION, ID_MUNICIPIO_EXPEDICION_DOCUM, FECHA_EXPEDICION_DOCUMENTO, FECHA_NACIMIENTO, FECHA_FALLECIMIENTO, NUMERO_TELEFONICO, ID_ESTADO_CIVIL, GENERO, APELLIDO1, APELLIDO2, NOMBRE1, NOMBRE2, CORREO_ELECTRONICO, NUMERO_CELULAR, NOMBRE_EMPRESA_LABORA, NOTIF_DIREC_EMPRE_LABOR, CARGO_EMPRESA_LABORA, TELEFONO_EMPRESA_LABORA, FAX_EMPRESA_LABORA, HUELLA_DIGITAL, RUTA_FOTO, FECHA_FOTO, CODIGO_TIPO_VIVIENDA, CODIGO_NIVEL_EDUCATIVO) VALUES ('-1', '2', '10000000001', '2', '11001', '2014-06-04', '1', '2014-06-04', '2014-06-04', NULL, '1000001', '2', 'F', 'apellido1_01', 'apellido2_01', 'nombre1_01', 'nombre2_01', 'nombre1_01@datatools.com.co', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', '1');
-- 
--  persona_juridica
-- 
INSERT INTO persona_juridica (ID_PERSONA_JURIDICA, DIGITO_VERIFICACION, NOMBRE_COMERCIAL, SIGLA, ID_CLASE_ACTIVIDAD_ECONOMICA, ID_MUNICIPIO) VALUES ('-1', '6', 'PERSONA JURÍDICA', 'PJ', '379', '149');

-- 
--  persona
-- 
INSERT INTO persona (ID_PERSONA, ID_TIPO_IDENTIFICACION, NUMERO_IDENTIFICACION, CODIGO_FUENTE_INFORMACION, CODIGO_ORGANISMO, FECHA_ULTIMA_ACTUALIZACION, ID_MUNICIPIO_EXPEDICION_DOCUM, FECHA_EXPEDICION_DOCUMENTO, FECHA_NACIMIENTO, FECHA_FALLECIMIENTO, NUMERO_TELEFONICO, ID_ESTADO_CIVIL, GENERO, APELLIDO1, APELLIDO2, NOMBRE1, NOMBRE2, CORREO_ELECTRONICO, NUMERO_CELULAR, NOMBRE_EMPRESA_LABORA, NOTIF_DIREC_EMPRE_LABOR, CARGO_EMPRESA_LABORA, TELEFONO_EMPRESA_LABORA, FAX_EMPRESA_LABORA, HUELLA_DIGITAL, RUTA_FOTO, FECHA_FOTO, CODIGO_TIPO_VIVIENDA, CODIGO_NIVEL_EDUCATIVO) VALUES ('-2', '2', '10000000002', '2', '11001', '2014-06-04', '1', '2014-06-04', '2014-06-04', NULL, '1000002', '2', 'F', 'apellido1_02', 'apellido2_02', 'nombre1_02', 'nombre2_02', 'nombre2_01@datatools.com.co', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', '1');
-- 
--  persona_juridica
-- 
INSERT INTO persona_juridica (ID_PERSONA_JURIDICA, DIGITO_VERIFICACION, NOMBRE_COMERCIAL, SIGLA, ID_CLASE_ACTIVIDAD_ECONOMICA, ID_MUNICIPIO) VALUES ('-2', '6', 'PERSONA JURÍDICA 2', 'PJ', '379', '149');

-- 
--  organismo_transito
-- 
INSERT INTO organismo_transito (CODIGO_ORGANISMO, NIT, NOMBRE_ORGANISMO, ACTIVO) VALUES (11001, '11001', 'ORGANISMO DE TRÁNSITO', TRUE);
INSERT INTO organismo_transito (CODIGO_ORGANISMO, NIT, NOMBRE_ORGANISMO, ACTIVO) VALUES (11002, '11002', 'ORGANISMO DE TRÁNSITO 2', TRUE);
-- 
--  Responsable_formulario
-- 
INSERT INTO responsable_formulario (id_responsable_formulario,fecha_inicio_vincula,fecha_fin_vincula,correo_responsable_formulario,id_tipo_responsable,codigo_organismo) VALUES (-1,'2015-01-01',null,'luis.forero@datatools.com.co',2,11001);
INSERT INTO responsable_formulario (id_responsable_formulario,fecha_inicio_vincula,fecha_fin_vincula,correo_responsable_formulario,id_tipo_responsable,codigo_organismo) VALUES (-2,'2015-01-01',null,'luis.forero@datatools.com.co',2,11001);

INSERT INTO unificacion_responsable (id_unificacion_responsable,id_persona,codigo_organismo,id_responsable_formulario) values (-1,-2,null,-1);
INSERT INTO unificacion_responsable (id_unificacion_responsable,id_persona,codigo_organismo,id_responsable_formulario) values (-2,null,11002,-2);
