-- 
--  relacion_estados
-- 
INSERT INTO relacion_estados (ID_RELACION_ESTADOS, ID_ESTADO_FORMULARIO_ACTUAL, ID_ESTADO_FORMULARIO_SIGUIENTE, ID_TIPO_FORMULARIO, CODIGO_ORGANISMO) VALUES ('-1', '1', '4', '5', '11001');
INSERT INTO relacion_estados (ID_RELACION_ESTADOS, ID_ESTADO_FORMULARIO_ACTUAL, ID_ESTADO_FORMULARIO_SIGUIENTE, ID_TIPO_FORMULARIO, CODIGO_ORGANISMO) VALUES ('-2', '1', '2', '5', '11001');
INSERT INTO relacion_estados (ID_RELACION_ESTADOS, ID_ESTADO_FORMULARIO_ACTUAL, ID_ESTADO_FORMULARIO_SIGUIENTE, ID_TIPO_FORMULARIO, CODIGO_ORGANISMO) VALUES ('-3', '1', '3', '5', '11001');