--   --------------------------------------------------
--   Insercion de datos base usuario super-admin
--   04_datos_menu.sql
--   -------------------------------------------------- 

INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (45, 13 , 2 ,'<map>\n  <entry>\n    <string>icon</string>\n    <string>ui-icon-person</string>\n  </entry>\n  <entry>\n    <string>label</string>\n    <string>Usuarios</string>\n  </entry>\n</map>',NULL);
INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (46, 13 , 1 ,'<map>\n  <entry>\n    <string>icon</string>\n    <string>ui-icon-note</string>\n  </entry>\n  <entry>\n    <string>label</string>\n    <string>Consultar Usuarios</string>\n  </entry>\n</map>',45);
INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (47, 13 , 2 ,'<map>\n  <entry>\n    <string>icon</string>\n    <string>ui-icon-plusthick</string>\n  </entry>\n  <entry>\n    <string>stateId</string>\n    <string>crear</string>\n  </entry>\n  <entry>\n    <string>label</string>\n    <string>Crear Usuario</string>\n  </entry>\n</map>',45);
INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (48, 17 , 7 ,'<map>\n  <entry>\n    <string>icon</string>\n    <string>ui-icon-calculator</string>\n  </entry>\n  <entry>\n    <string>label</string>\n    <string>Operaciones</string>\n  </entry>\n</map>',NULL);
INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (49, 17 , 1 ,'<map>\n  <entry>\n    <string>icon</string>\n    <string>ui-icon-note</string>\n  </entry>\n  <entry>\n    <string>label</string>\n    <string>Consultar Operación</string>\n  </entry>\n</map>',48);
INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (50, 17 , 2 ,'<map>\n  <entry>\n    <string>icon</string>\n    <string>ui-icon-plusthick</string>\n  </entry>\n  <entry>\n    <string>stateId</string>\n    <string>crear</string>\n  </entry>\n  <entry>\n    <string>label</string>\n    <string>Crear Operación</string>\n  </entry>\n</map>',48);
INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (51, 15 , 5 ,'<map>\n  <entry>\n    <string>icon</string>\n    <string>ui-icon-wrench</string>\n  </entry>\n  <entry>\n    <string>label</string>\n    <string>Recursos</string>\n  </entry>\n</map>',NULL);
INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (52, 15 , 1 ,'<map>\n  <entry>\n    <string>icon</string>\n    <string>ui-icon-note</string>\n  </entry>\n  <entry>\n    <string>label</string>\n    <string>Consultar Recursos</string>\n  </entry>\n</map>',51);
INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (53, 15 , 2 ,'<map>\n  <entry>\n    <string>icon</string>\n    <string>ui-icon-plusthick</string>\n  </entry>\n  <entry>\n    <string>stateId</string>\n    <string>crear</string>\n  </entry>\n  <entry>\n    <string>label</string>\n    <string>Crear Recurso</string>\n  </entry>\n</map>',51);
INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (54, 14 , 3 ,'<map>\n  <entry>\n    <string>icon</string>\n    <string>ui-icon-gear</string>\n  </entry>\n  <entry>\n    <string>label</string>\n    <string>Roles</string>\n  </entry>\n</map>',NULL);
INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (55, 14 , 1 ,'<map>\n  <entry>\n    <string>icon</string>\n    <string>ui-icon-note</string>\n  </entry>\n  <entry>\n    <string>label</string>\n    <string>Consultar Roles</string>\n  </entry>\n</map>',54);
INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (56, 14 , 2 ,'<map>\n  <entry>\n    <string>icon</string>\n    <string>ui-icon-plusthick</string>\n  </entry>\n  <entry>\n    <string>stateId</string>\n    <string>crear</string>\n  </entry>\n  <entry>\n    <string>label</string>\n    <string>Crear Rol</string>\n  </entry>\n</map>',54);
INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (57, 16 , 4 ,'<map>\n  <entry>\n    <string>icon</string>\n    <string>ui-icon-contact</string>\n  </entry>\n  <entry>\n    <string>label</string>\n    <string>Grupos</string>\n  </entry>\n</map>',NULL);
INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (58, 16 , 1 ,'<map>\n  <entry>\n    <string>icon</string>\n    <string>ui-icon-note</string>\n  </entry>\n  <entry>\n    <string>label</string>\n    <string>Consultar Grupos</string>\n  </entry>\n</map>',57);
INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (59, 16 , 2 ,'<map>\n  <entry>\n    <string>icon</string>\n    <string>ui-icon-plusthick</string>\n  </entry>\n  <entry>\n    <string>stateId</string>\n    <string>crear</string>\n  </entry>\n  <entry>\n    <string>label</string>\n    <string>Crear Grupo</string>\n  </entry>\n</map>',57);
INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (60, 18 , 7 ,'<map>\n  <entry>\n    <string>icon</string>\n    <string>ui-icon-flag</string>\n  </entry>\n  <entry>\n    <string>label</string>\n    <string>Menú</string>\n  </entry>\n</map>',NULL);
INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (61, 1  , 1 ,'<map>\n  <entry>\n    <string>icon</string>\n    <string>ui-icon-home</string>\n  </entry>\n  <entry>\n    <string>label</string>\n    <string>Inicio</string>\n  </entry>\n</map>',NULL);
INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (62, 12 , 9 ,'<map>\n  <entry>\n    <string>icon</string>\n    <string>ui-icon-locked</string>\n  </entry>\n  <entry>\n    <string>label</string>\n    <string>Mi Cuenta</string>\n  </entry>\n</map>',NULL);
INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (63, 20 , 10,'<map>\n  <entry>\n    <string>icon</string>\n    <string>ui-icon-clipboard</string>\n  </entry>\n  <entry>\n    <string>label</string>\n    <string>Parámetros</string>\n  </entry>\n</map>',NULL);
INSERT INTO recurso_menu (ID_RECURSO_MENU,ID_RECURSO,ORDEN,RECURSO_DATA,ID_MENU_PADRE) VALUES (64, 21 , 11, '<map><entry><string>icon</string>    <string>ui-icon-flag</string>  </entry>  <entry>    <string>label</string>    <string>Ingresos</string>  </entry></map>', NULL);
